import { Course } from '@/types/course';

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'Robotics Fundamentals for Beginners',
    description: 'An introductory course to the exciting world of robotics for younger students.',
    longDescription: 'This course introduces young learners to the fascinating world of robotics through engaging hands-on activities. Students will learn basic robot design, simple mechanics, and introductory programming using block-based coding interfaces. Through fun challenges and collaborative projects, participants will develop foundation skills in problem-solving and computational thinking while building and programming their very own robots. Perfect for curious minds with no prior experience in robotics or coding.',
    ageRange: { min: 7, max: 9 },
    skillLevel: 'Beginner',
    topics: ['Robot Design', 'Block Coding', 'Basic Electronics'],
    duration: '2 weeks',
    schedule: {
      startDate: '2025-06-15',
      endDate: '2025-06-26',
      days: ['Monday', 'Wednesday', 'Friday'],
      timeSlot: '9:00 AM - 12:00 PM',
    },
    instructor: {
      name: 'Dr. Emily Chen',
      bio: 'Dr. Chen has 10 years of experience teaching STEM to elementary school students.',
      image: 'https://via.placeholder.com/150',
    },
    price: 299,
    discountedPrice: 254,
    capacity: 15,
    enrolledCount: 8,
    image: 'https://via.placeholder.com/800x600',
    featured: true,
  },
  {
    id: '2',
    title: 'Advanced Robotics Engineering',
    description: 'A deep dive into complex robotics systems for experienced students.',
    longDescription: 'Designed for students with prior robotics experience, this advanced course explores sophisticated concepts in robot engineering and automation. Participants will work with advanced sensors, motorized systems, and learn text-based programming to create robots capable of autonomous navigation and complex task execution. The curriculum includes advanced mechanics, electronic circuit design, and the principles of artificial intelligence in robotics. Students will complete a capstone project that demonstrates their mastery of multiple robotics concepts.',
    ageRange: { min: 13, max: 16 },
    skillLevel: 'Advanced',
    topics: ['Autonomous Systems', 'Python Programming', 'AI Basics'],
    duration: '3 weeks',
    schedule: {
      startDate: '2025-07-10',
      endDate: '2025-07-31',
      days: ['Tuesday', 'Thursday'],
      timeSlot: '1:00 PM - 4:30 PM',
    },
    instructor: {
      name: 'Prof. James Wilson',
      bio: 'Robotics researcher with experience at leading technology companies.',
      image: 'https://via.placeholder.com/150',
    },
    price: 499,
    capacity: 12,
    enrolledCount: 5,
    image: 'https://via.placeholder.com/800x600',
    featured: true,
  },
  {
    id: '3',
    title: 'Creative Robotics & Design',
    description: 'Combine art and engineering to create unique interactive robots.',
    longDescription: 'This unique course bridges the gap between technology and creativity, teaching students to integrate artistic elements into their robotic creations. Participants will learn how to design and build robots with aesthetic appeal while maintaining functionality. The curriculum covers the use of various materials, 3D design principles, and how to incorporate lights, sounds, and movements to create expressive robotic sculptures and interactive installations. Ideal for students interested in both technology and visual arts.',
    ageRange: { min: 10, max: 14 },
    skillLevel: 'Intermediate',
    topics: ['3D Design', 'Interactive Art', 'Sound & Movement'],
    duration: '2 weeks',
    schedule: {
      startDate: '2025-06-15',
      endDate: '2025-06-26',
      days: ['Monday', 'Wednesday', 'Friday'],
      timeSlot: '1:00 PM - 4:00 PM',
    },
    instructor: {
      name: 'Maria Rodriguez',
      bio: 'Award-winning artist specializing in interactive robotic installations.',
      image: 'https://via.placeholder.com/150',
    },
    price: 349,
    discountedPrice: 297,
    capacity: 12,
    enrolledCount: 7,
    image: 'https://via.placeholder.com/800x600',
    featured: false,
  },
  {
    id: '4',
    title: 'Robotics Competition Prep',
    description: 'Prepare for robotics competitions with team-based challenges.',
    longDescription: 'Designed for students interested in competitive robotics, this intense course focuses on the skills and strategies needed for success in robotics competitions. Students will work in teams to design, build, and program robots that can complete specific challenges under time constraints. The curriculum covers competition regulations, strategic planning, efficient design iterations, and collaborative problem-solving. Participants will gain experience in real competition scenarios through practice rounds and a final tournament-style event.',
    ageRange: { min: 12, max: 16 },
    skillLevel: 'Intermediate',
    topics: ['Competition Strategy', 'Team Collaboration', 'Time Management'],
    duration: '4 weeks',
    schedule: {
      startDate: '2025-07-05',
      endDate: '2025-08-01',
      days: ['Monday', 'Wednesday', 'Friday'],
      timeSlot: '9:00 AM - 1:00 PM',
    },
    instructor: {
      name: 'Thomas Lee',
      bio: 'Former national robotics competition champion and coach.',
      image: 'https://via.placeholder.com/150',
    },
    price: 449,
    capacity: 20,
    enrolledCount: 15,
    image: 'https://via.placeholder.com/800x600',
    featured: false,
  },
  {
    id: '5',
    title: 'Introduction to AI & Robotics',
    description: 'Learn how artificial intelligence powers modern robotics systems.',
    longDescription: 'This course introduces students to the exciting intersection of artificial intelligence and robotics. Participants will learn how AI algorithms enable robots to perceive, learn, and interact with their environment. Through hands-on projects, students will implement basic machine learning concepts, computer vision techniques, and natural language processing for robotic applications. The curriculum balances theoretical understanding with practical implementation, making complex AI concepts accessible to young learners.',
    ageRange: { min: 12, max: 16 },
    skillLevel: 'Intermediate',
    topics: ['Machine Learning', 'Computer Vision', 'Neural Networks'],
    duration: '3 weeks',
    schedule: {
      startDate: '2025-07-07',
      endDate: '2025-07-25',
      days: ['Monday', 'Wednesday', 'Friday'],
      timeSlot: '9:00 AM - 12:00 PM',
    },
    instructor: {
      name: 'Dr. Alex Patel',
      bio: 'AI researcher with a passion for educating the next generation of innovators.',
      image: 'https://via.placeholder.com/150',
    },
    price: 399,
    discountedPrice: 339,
    capacity: 15,
    enrolledCount: 9,
    image: 'https://via.placeholder.com/800x600',
    featured: true,
  },
  {
    id: '6',
    title: 'Robotics for Young Innovators',
    description: 'A fun introduction to robotics concepts for our youngest participants.',
    longDescription: 'Specifically designed for our youngest innovators, this course makes robotics accessible and engaging for elementary school students. Through playful activities and simplified building kits, children will learn basic robotic concepts, simple programming logic, and creative problem-solving. The curriculum emphasizes collaboration, creativity, and fun while introducing fundamental STEM concepts. Students will build confidence in their technical abilities while developing a passion for technology and engineering.',
    ageRange: { min: 7, max: 9 },
    skillLevel: 'Beginner',
    topics: ['Basic Building', 'Simple Coding', 'Teamwork'],
    duration: '2 weeks',
    schedule: {
      startDate: '2025-06-15',
      endDate: '2025-06-26',
      days: ['Tuesday', 'Thursday'],
      timeSlot: '9:30 AM - 11:30 AM',
    },
    instructor: {
      name: 'Sarah Johnson',
      bio: 'Elementary education specialist with a background in early STEM learning.',
      image: 'https://via.placeholder.com/150',
    },
    price: 249,
    capacity: 10,
    enrolledCount: 6,
    image: 'https://via.placeholder.com/800x600',
    featured: false,
  },
  {
    id: '7',
    title: 'Robotic Automation Systems',
    description: 'Design and build automated systems to solve real-world problems.',
    longDescription: 'This specialized course focuses on the principles and applications of automated robotic systems. Students will learn to design, program, and implement robotic solutions for real-world automation challenges. The curriculum covers sensors and feedback mechanisms, programming logical sequences, and integrating multiple components into a functioning system. Participants will develop projects that demonstrate industrial automation concepts on a smaller scale, such as sorting systems, assembly lines, or material handling solutions.',
    ageRange: { min: 13, max: 16 },
    skillLevel: 'Advanced',
    topics: ['Industrial Automation', 'Systems Design', 'Sensor Networks'],
    duration: '3 weeks',
    schedule: {
      startDate: '2025-07-10',
      endDate: '2025-07-31',
      days: ['Monday', 'Wednesday', 'Friday'],
      timeSlot: '1:00 PM - 4:00 PM',
    },
    instructor: {
      name: 'Robert Chang',
      bio: 'Automation engineer with experience in manufacturing robotics.',
      image: 'https://via.placeholder.com/150',
    },
    price: 429,
    capacity: 12,
    enrolledCount: 4,
    image: 'https://via.placeholder.com/800x600',
    featured: false,
  },
  {
    id: '8',
    title: 'Drone Building & Programming',
    description: 'Learn to build, customize, and program aerial robotics systems.',
    longDescription: 'This specialized course takes robotics to new heights as students learn to build and program their own drone systems. Participants will explore the principles of flight, drone components and design, and programming for autonomous flight paths. The curriculum covers safety considerations, basic aerodynamics, electronic control systems, and practical applications of drone technology. Students will customize their drones with various sensors and cameras to complete aerial challenges and capture footage from a new perspective.',
    ageRange: { min: 12, max: 16 },
    skillLevel: 'Intermediate',
    topics: ['Aerial Robotics', 'Flight Control', 'Navigation Systems'],
    duration: '2 weeks',
    schedule: {
      startDate: '2025-07-07',
      endDate: '2025-07-18',
      days: ['Tuesday', 'Thursday'],
      timeSlot: '9:00 AM - 12:30 PM',
    },
    instructor: {
      name: 'David Martinez',
      bio: 'Certified drone pilot and robotics educator with aerospace background.',
      image: 'https://via.placeholder.com/150',
    },
    price: 479,
    discountedPrice: 407,
    capacity: 10,
    enrolledCount: 8,
    image: 'https://via.placeholder.com/800x600',
    featured: true,
  },
];